### PR TITLE
Expand derived clusters

### LINKED ISSUE #462: Unexpected token error processing SVD file
[RA6M2.zip](https://github.com/rust-embedded/svd2rust/files/5033887/RA6M2.zip)

I am trying to process the RA6M2.svd file.

This requires changes to the svd-parser that I have already reported and to register.rs file, which I have attached, to filter out enumerated values without a value element.

When I run svd2rust with these modification I get a [ERROR svd2rust] unexpected token

### PR DESCRIPTION
**Pull request by smindinvern**
This PR addresses two issues encountered when attempting to process the svd file [here](https://raw.githubusercontent.com/renesas/fsp/master/ra/fsp/src/bsp/cmsis/Device/RENESAS/SVD/RA.svd).

1.  The SVD file defines a cluster in the 'R_GPT_ODC' peripheral that derives from a sibling cluster.  AFAICT from the SVD schema, this is allowed, and we should expand the cluster definition in the same way registers are handled.
2.  The SVD file contains many `EnumeratedValue`s that are "reserved", but aren't filtered out because they're named "other".  They have an `<isDefault>` child element, which is mutually exclusive with the `<value>` child element according to the SVD schema, i.e. they don't represent a value that we would want to define in the generated code, and so can be skipped.

When running `svd2rust-regress` locally 3 tests fail, but the same tests also fail on `master`, so it seems there's no indication of a regression here.

This seems to fix #462.

### CODE REVIEW

**Comment by burrbull** [comment]
LGTM.
Rustfmt, please.

**Comment by smindinvern** [comment]
I noticed that this causes invalid rust code to be generated for fields which only have a single `isDefault` value.  I have a patch for that, but I'm not sure that it's correct.  Should I include that here for consideration, or address that separately?

**Comment by burrbull** [comment]
I think it's better to split this PR. And place c9b18c7165523c610efb84bd2eed61658dbe05eb in other one.

File: src/generate/register.rs [hunk 1]
```diff
@@ -771,9 +771,9 @@ impl Variant {
         let span = Span::call_site();
         evs.values
             .iter()
-            // filter out all reserved variants, as we should not
+            // filter out all reserved or default variants, as we should not
             // generate code for them
-            .filter(|field| field.name.to_lowercase() != "reserved")
+            .filter(|field| field.name.to_lowercase() != "reserved" && field.is_default == None)
```
Comment (Emilgardis) [inline src/generate/register.rs:776]: This will fail in some cases as noted. A suggestion is to run svd2rust-regress and then diff the outputs, that can help with determining validity of change.

**Review by Emilgardis — CHANGES_REQUESTED** [review]
Nice!

Rebase to squash rustfmt and remove c9b18c7165523c610efb84bd2eed61658dbe05eb

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
@Emilgardis

**Review by Emilgardis — APPROVED** [review]

**Comment by Emilgardis** [comment]
bors r=burrbull

**Comment by therealprof** [comment]
@smindinvern And of course I missed that this is missing a CHANGELOG entry. Would you mind PRing one? 😅
