### PR TITLE
Simplify Interrupt::nr

### LINKED ISSUE #211: Use custom discriminant values for Interrupts enum
I wondered why the `Nr` trait is implemented so complicated and long-winded with the `match` lookup. Wouldn't it be easier, and more performant (or: less reliant on compiler optimisations), to just use [Custom Discriminant Values](https://doc.rust-lang.org/reference/items/enumerations.html#custom-discriminant-values-for-field-less-enumerations) in the `enum` declaration - to allow a direct cast to/from an integer? Maybe even `#repr(u8)`?
If this sounds reasonable, I'll try to make a PR, it seems doable for a beginner like me.

Or maybe it would be nice to go even further and not use the "*IRQ number*" (as defined by CMSIS and represented in the [`Nr` trait](https://docs.rs/bare-metal/0.1.2/bare_metal/trait.Nr.html)) but the raw "*exception number*" as in the `IPSR`, `ICSR.VECTPENDING`, and `ICSR.VECTACTIVE` register fields. This would require an offset of 16, but I know only about Cortex-M4 machines. How about other processor types supported by svd2rust?

### LINKED ISSUE #370: Suboptimal code generated for Interrupt numbers
To contextualize, I'm using the nrf52840-pac crate version 0.8.0 (generated by svd2rust v0.14.0 but I think the issue still applies to the latest) and compiled using rustc 1.37.0-nightly (0af8e872e 2019-06-30) with `codegen-units=1`, `debug=true`, `lto=true`, and `opt-level="z"`. Now, with that out of the way.

The Interrupt enum has a variant for each hardware interrupt with a doc tag containing its number and lets the compiler assign the discriminant. To get the number from the enum variant, the `nr(&self) -> u8` function matches each variant to the hardware interrupt number. Unfortunately, the compiler turns this lookup into a jump table instead of encoding the interrupt number in the discriminant (perhaps because the interrupt numbers on the mentioned chip are discontinuous), wasting five bytes per interrupt plus the overhead of having a function do the work.

I manually changed the crate to set the discriminant of each variant to the interrupt number, but the compiled code did not change. I then changed the body of `nr(&self) -> u8` to `*self as u8` instead of the match and reduced code size by 304 bytes. Perhaps the generation should be changed so the code is generated in this form? That's a significant savings for a small transformation.

### PR DESCRIPTION
**Pull request by roblabla**
Make the Interrupt enum descriminant match the interrupt nr directly. This allows simplifying Interrupt::nr from being a complicated match to a simple cast to an u8.

According to #370, this should lead to a code reduction of as much as 304 bytes.

Fixes #211
Fixes #370

### CODE REVIEW

File: src/generate/interrupt.rs [hunk 1]
```diff
@@ -161,9 +156,7 @@ pub fn render(
         unsafe impl bare_metal::Nr for Interrupt {
             #[inline]
```
Comment (burrbull) [inline src/generate/interrupt.rs]:
```suggestion
             #[inline(always)]
```

File: src/generate/interrupt.rs [hunk 2]
```diff
@@ -161,9 +156,7 @@ pub fn render(
         unsafe impl bare_metal::Nr for Interrupt {
```
Comment (burrbull) [inline src/generate/interrupt.rs]:
```suggestion
         #[repr(u8)]
         unsafe impl bare_metal::Nr for Interrupt {
```

Comment (roblabla) [reply src/generate/interrupt.rs]: I suppose this should go on the enum and not on the impl?

Comment (burrbull) [reply src/generate/interrupt.rs]: yes

**Comment by roblabla** [comment]
bors try

**Comment by therealprof** [comment]
@roblabla You should now have try permissions.

**Comment by burrbull** [comment]
bors try

**Comment by roblabla** [comment]
Repr u8 seems to not work on uninhabited enums. Guess I’ll have to put the repr only if the interrupt enum is not empty?

**Comment by burrbull** [comment]
> Repr u8 seems to not work on uninhabited enums. Guess I’ll have to put the repr only if the interrupt enum is not empty?

reasonably

**Comment by roblabla** [comment]
bors try

**Comment by roblabla** [comment]
bors try

**Comment by roblabla** [comment]
bors try

**Comment by roblabla** [comment]
bors try

**Comment by burrbull** [comment]
bors retry

**Comment by therealprof** [comment]
@roblabla Sorry I missed it earlier, but please squash your commits the next time so we don't have broken commits in the history.
